[package]
name = "scrapydoo"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "*"
thread = "*"
jwalk = "*"
elasticsearch = "7.14.0-alpha.1"
serde_json = "*"
serde = "*"
url = "^2.1"
sysinfo = "0.12.0"
tokio = { version = "1", features = ["full"] }
